### ISSUE TITLE
MQTT Missing 

### ISSUE THREAD

**Issue by electronicm** [mercenaruss/uzg-manual#1]
The documentation for the MQTT menu item is missing.

**Comment by electronicm** [comment]
"System and Tools" > "Firmware update" link to https://uzg.zig-star.com/flashing-and-updating/
Or 
"MQTT" link to the docu from https://github.com/mercenaruss/uzg-manual/issues/1

In this way you could create an extensive documentation and the code of the web interface would remain as small as possible.

**Comment by electronicm** [comment]
"System and Tools" > "Firmware update" link to https://uzg.zig-star.com/flashing-and-updating/
Or 
"MQTT" link to the docu from https://github.com/mercenaruss/uzg-manual/issues/1

In this way you could create an extensive documentation and the code of the web interface would remain as small as possible.

**Comment by mercenaruss** [comment]
Will be added,trying now to figure out how to implement uzg-01 software and documentation together.
